name: daily-option-scan
on:
  schedule: [{cron: "30 1 * * 1-5"}] # 香港9:30開市
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install requests scipy
      - run: python main.py
        env:
          FUTU_PWD: ${{ secrets.FUTU_PWD }}
          FUTU_ID: ${{ secrets.FUTU_ID }}
