name: scan
on:
  workflow_dispatch:
    inputs:
      stock_code:
        description: '股票號碼 700/1299/2800/388'
        required: true
        default: '00700'
        type: string
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - run: pip install requests beautifulsoup4 lxml
      - run: python main.py ${{ inputs.stock_code }}
