name: daily-option-scan
on: 
  workflow_dispatch:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install requests scipy yfinance
          touch sources/__init__.py
      - name: Run scan
        run: python main.py
        env:
          FUTU_PWD: ${{ secrets.FUTU_PWD }}
          FUTU_ID: ${{ secrets.FUTU_ID }}
